### ISSUE TITLE
陀螺儀無法使用

### ISSUE THREAD

**Issue by karakarasuuuu** [rogeraabbccdd/AsiaGodTone-Hotpot-Game#1]
如題，在 iPhone 11 / Xr / 8 的 Safari 跟 Chrome 都不能用陀螺儀操控。
（下面的數字沒有變應該是沒有動的意思吧？）

**Comment by rogeraabbccdd** [comment]
恩對，我剛剛測試在我的 iPad Pro iOS 14.4 的 Chrome 也沒辦法使用

**Comment by rogeraabbccdd** [comment]
看起來應該是 iOS 14 不支援，沒辦法

**Comment by pan93412** [comment]
> 看起來應該是 iOS 14 不支援，沒辦法



> 如題，在 iPhone 11 / Xr / 8 的 Safari 跟 Chrome 都不能用陀螺儀操控。
> （下面的數字沒有變應該是沒有動的意思吧？）

建議你先到[這個測試網站](https://www.audero.it/demo/device-orientation-api-demo.html)看看能不能動。如果不能動的話應該就是 iOS 的問題，如果可以應該就是 @rogeraabbccdd 程式的問題。

[理論上應該可以運作。](https://developer.apple.com/documentation/webkitjs/deviceorientationevent)

**Comment by hsiungyuu** [comment]
我也認為理論上是可以動的
不過我的I7也是無法run

**Comment by karakarasuuuu** [comment]
> > 看起來應該是 iOS 14 不支援，沒辦法
> 
> > 如題，在 iPhone 11 / Xr / 8 的 Safari 跟 Chrome 都不能用陀螺儀操控。
> > （下面的數字沒有變應該是沒有動的意思吧？）
> 
> 建議你先到[這個測試網站](https://www.audero.it/demo/device-orientation-api-demo.html)看看能不能動。如果不能動的話應該就是 iOS 的問題，如果可以應該就是 @rogeraabbccdd 程式的問題。
> 
> [理論上應該可以運作。](https://developer.apple.com/documentation/webkitjs/deviceorientationevent)

我這個網站也不能運作欸，看來是 iOS 的問題？

**Comment by pan93412** [comment]
> > > 看起來應該是 iOS 14 不支援，沒辦法
> > 
> > > 如題，在 iPhone 11 / Xr / 8 的 Safari 跟 Chrome 都不能用陀螺儀操控。
> > > （下面的數字沒有變應該是沒有動的意思吧？）
> > 
> > 建議你先到[這個測試網站](https://www.audero.it/demo/device-orientation-api-demo.html)看看能不能動。如果不能動的話應該就是 iOS 的問題，如果可以應該就是 @rogeraabbccdd 程式的問題。
> > 
> > [理論上應該可以運作。](https://developer.apple.com/documentation/webkitjs/deviceorientationevent)
> 
> 我這個網站也不能運作欸，看來是 iOS 的問題？

那就不行。 @rogeraabbccdd Android 11 無法正常運作，但測試網頁可以。有沒有考慮把 issue title 改成 android 11 specific？

**Comment by dannylin0711** [comment]
已經先發一個暫時的PR了 等待作者合併到vue裡面
原因是iOS 13以上必須透過特殊API 讓使用者允許使用陀螺儀的權限 不然無法使用

**Comment by rogeraabbccdd** [comment]
恩...我合併了 #14 之後才發現我的 iPad iOS 14 還是不行...

**Comment by dannylin0711** [comment]
能問一下是在哪裡測的嗎？
自架的伺服器嗎？還是GitHub Page上

**Comment by dannylin0711** [comment]
@pan93412 剛剛測試了一下 這樣改反而不行的樣子( 
我先Rollback到舊版去

**Comment by pan93412** [comment]
> @pan93412 剛剛測試了一下 這樣改反而不行的樣子(
> 我先Rollback到舊版去

可以。謝謝！

**Comment by dannylin0711** [comment]
#15 Rollback PR

**Comment by rogeraabbccdd** [comment]
> 能問一下是在哪裡測的嗎？
> 自架的伺服器嗎？還是GitHub Page上

GitHub Pages

**Comment by dannylin0711** [comment]
我剛剛也測了一下 所以回退到還沒合進去vue 的版本
我這邊也是測不過 沒有跳出要求權限的視窗
不過回退之後應該就會可以了

**Comment by rogeraabbccdd** [comment]
現在應該正常了
