### ISSUE TITLE
import 的 Vue網址找不到了

### ISSUE THREAD

**Issue by illuminechen** [rogeraabbccdd/AsiaGodTone-Hotpot-Game#16]
<script src="https://unpkg.com/vue@next"></script>
可以改成
<script src="https://unpkg.com/vue@3.5.11"></script>

**Comment by rogeraabbccdd** [comment]
已修正
https://github.com/rogeraabbccdd/AsiaGodTone-Hotpot-Game/commit/7c5d3a8786e1671a8f4a31ff53f0b1e55739631f
