### ISSUE TITLE
是否有考慮改用基於 Webpack 的 vue-cli 重構程式

### ISSUE THREAD

**Issue by pan93412** [rogeraabbccdd/AsiaGodTone-Hotpot-Game#4]
如果有興趣的話，我明天可以試著重構看看。此外也想套上 TypeScript 之類的東西。

**Comment by rogeraabbccdd** [comment]
我當初做的時候是想說小東西而已，不需要出動 webpack  
用 vue-cli 應該也可以，用 pug 之類的預處理器寫蠻省力的，也能打包成 electron 之類有的沒的

**Comment by pan93412** [comment]
> 我當初做的時候是想說小東西而已，不需要出動 webpack
> 用 vue-cli 應該也可以，用 pug 之類的預處理器寫蠻省力的，也能打包成 electron 之類有的沒的

Pug 我不太推薦耶。之前試過 Webpack w/ Pug，但發現到 Pug 的某些功能沒辦法在 Webpack 下正常運作，而且 Pug 很多功能跟 Vue 的 attribute 語法重疊。

**Comment by rogeraabbccdd** [comment]
我用 Vue-Cli 配 pug 用一年多了，還沒遇到什麼大問題...  
語法重疊的部分，像是 pug 的 `each val in` 和 `v-for` 的迴圈我會以 Vue 的語法優先

**Comment by pan93412** [comment]
> 我用 Vue-Cli 配 pug 用一年多了，還沒遇到什麼大問題...
> 語法重疊的部分，像是 pug 的 `each val in` 和 `v-for` 的迴圈我會以 Vue 的語法優先

原來你試過了喔 OAO 而且聽起來 Vue w/ Pug 的組合沒什麼問題，那就試試看吧。

Pug on Webpack 我以前碰到的主要是 variable scope 問題啦。

**Comment by rogeraabbccdd** [comment]
我最近做的 [techmania](https://github.com/techmania-team/techmania-team.github.io) 就是用 Quasar Framework + Pug + Stylus

**Comment by pan93412** [comment]
> 我最近做的 [techmania](https://github.com/techmania-team/techmania-team.github.io) 就是用 Quasar Framework + Pug + Stylus

好酷，是音遊耶！
